#pragma once

#define COMPOSERGUI_MAIN_WINDOW_BACKGROUND "background: #262831;"
#define COMPOSERGUI_MAIN_WINDOW_STYLESHEET "background: #262831; color: #9ea1b3;"

#define COMPOSERGUI_WIDGET_STYLESHEET "background: #2d2f39;color: #9ea1b3;"
#define COMPOSERGUI_WIDGET_BACKGROUND "background: #2d2f39;"

#define COMPOSERGUI_CONSOLE_PROCESSING_TEXT_COLOR "#00ff00"
#define COMPOSERGUI_DEFAULT_TEXT_COLOR "#9ea1b3"

#define COMPOSERGUI_ORGANIZATION_NAME "ComposerGUI"
#define COMPOSERGUI_SETTINGS_PROJECT "Projects"
#define COMPOSERGUI_SETTINGS_APPLICATION "Application"

#define COMPOSERGUI_PACKAGE_PACKGROUND "background: #383b47;"
#define COMPOSERGUI_PACKAGE_DESCRIPTION_STYLESHEET "font-style: italic;"
